/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YdelserRouteImport } from './routes/ydelser'
import { Route as OmRouteImport } from './routes/om'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ErfaringRouteImport } from './routes/erfaring'
import { Route as IndexRouteImport } from './routes/index'

const YdelserRoute = YdelserRouteImport.update({
  id: '/ydelser',
  path: '/ydelser',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ErfaringRoute = ErfaringRouteImport.update({
  id: '/erfaring',
  path: '/erfaring',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/erfaring': typeof ErfaringRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/ydelser': typeof YdelserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/erfaring': typeof ErfaringRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/ydelser': typeof YdelserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/erfaring': typeof ErfaringRoute
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/ydelser': typeof YdelserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/erfaring' | '/kontakt' | '/om' | '/ydelser'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/erfaring' | '/kontakt' | '/om' | '/ydelser'
  id: '__root__' | '/' | '/erfaring' | '/kontakt' | '/om' | '/ydelser'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErfaringRoute: typeof ErfaringRoute
  KontaktRoute: typeof KontaktRoute
  OmRoute: typeof OmRoute
  YdelserRoute: typeof YdelserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ydelser': {
      id: '/ydelser'
      path: '/ydelser'
      fullPath: '/ydelser'
      preLoaderRoute: typeof YdelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erfaring': {
      id: '/erfaring'
      path: '/erfaring'
      fullPath: '/erfaring'
      preLoaderRoute: typeof ErfaringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErfaringRoute: ErfaringRoute,
  KontaktRoute: KontaktRoute,
  OmRoute: OmRoute,
  YdelserRoute: YdelserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
